name: Commit Changes to Another Repository

on:
  push:
    branches:
      - source-branch  # Branch where changes are pushed

jobs:
  commit_changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      
    - name: Clone target repository
      uses: actions/checkout@v2
      with:
        repository: username/target-repository
        ref: target-branch
        token: ${{ secrets.TARGET_REPO_ACCESS_TOKEN }}
        path: ./target-repo
      
    - name: Make changes
      run: |
        # Make changes here
        echo "New changes" >> ./target-repo/file.txt
      
    - name: Commit and push changes
      run: |
        cd ./target-repo
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Automated changes from source repository"
        git push origin target-branch
